version: "3.8"
services:
  db-agro:
    container_name: db-agro
    image: postgres:15.2
    restart: unless-stopped
    environment:
      # - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=wolf103
      - POSTGRES_PASSWORD=Donna103
      - POSTGRES_DB=agro_sus
    ports:
      - "5432:5432"
    expose:
      - 5432
    command: -p 5432
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      network:
        ipv4_address: 10.6.0.4

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: "orozcocristian860@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "Donna103"
    ports:
      - "5050:80"
    expose:
      - 5050
    depends_on:
      - db-agro
    networks:
      network:
        ipv4_address: 10.6.0.5

volumes:
  db:
    driver: local

networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: "10.6.0.0/24"
          gateway: 10.6.0.1