
INSERT INTO public.roles ( name) VALUES ('ROLE_OPERATOR');
INSERT INTO public.roles ( name) VALUES ('ROLE_ADMIN');
INSERT INTO public.roles ( name) VALUES ('ROLE_VISIT');

INSERT INTO public.locations ( name) VALUES ('Azara');
INSERT INTO public.locations ( name) VALUES ('Barrio Rural');
INSERT INTO public.locations ( name) VALUES ('Estación Apóstoles');
INSERT INTO public.locations ( name) VALUES ('Pindapoy');
INSERT INTO public.locations ( name) VALUES ('Rincón de Azara');
INSERT INTO public.locations ( name) VALUES ('San José');
INSERT INTO public.locations ( name) VALUES ('Tres Capones');
INSERT INTO public.locations ( name) VALUES ('Apóstoles');
INSERT INTO public.locations ( name) VALUES ('Aristóbulo del Valle');
INSERT INTO public.locations ( name) VALUES ('Campo Grande');
INSERT INTO public.locations ( name) VALUES ('Dos de Mayo');
INSERT INTO public.locations ( name) VALUES ('1º de Mayo');
INSERT INTO public.locations ( name) VALUES ('Pueblo Illia');
INSERT INTO public.locations ( name) VALUES ('Candelaria');
INSERT INTO public.locations ( name) VALUES ('Salto Encantado');
INSERT INTO public.locations ( name) VALUES ('Kilómetro 17');
INSERT INTO public.locations ( name) VALUES ('Dos de Mayo');
INSERT INTO public.locations ( name) VALUES ('Bonpland');
INSERT INTO public.locations ( name) VALUES ('Cerro Corá');
INSERT INTO public.locations ( name) VALUES ('Mártires');
INSERT INTO public.locations ( name) VALUES ('Profundidad');
INSERT INTO public.locations ( name) VALUES ('Puerto Santa Ana');
INSERT INTO public.locations ( name) VALUES ('Loreto');
INSERT INTO public.locations ( name) VALUES ('Santa Ana');
INSERT INTO public.locations ( name) VALUES ('Barrio del Lago');
INSERT INTO public.locations ( name) VALUES ('Garupá');
INSERT INTO public.locations ( name) VALUES ('Nemesio Parma');
INSERT INTO public.locations ( name) VALUES ('Posadas');
INSERT INTO public.locations ( name) VALUES ('Barra Concepción');
INSERT INTO public.locations ( name) VALUES ('Concepción de la Sierra');
INSERT INTO public.locations ( name) VALUES ('La Corita');
INSERT INTO public.locations ( name) VALUES ('Santa María');
INSERT INTO public.locations ( name) VALUES ('Colonia Victoria');
INSERT INTO public.locations ( name) VALUES ('María Magdalena');
INSERT INTO public.locations ( name) VALUES ('Nueva Delicia');
INSERT INTO public.locations ( name) VALUES ('9 de Julio Kilómetro 28');
INSERT INTO public.locations ( name) VALUES ('9 de Julio Kilómetro 20');
INSERT INTO public.locations ( name) VALUES ('Pueblo Nuevo');
INSERT INTO public.locations ( name) VALUES ('Puerto Mado');
INSERT INTO public.locations ( name) VALUES ('Puerto Pinares');
INSERT INTO public.locations ( name) VALUES ('Valle Hermoso');
INSERT INTO public.locations ( name) VALUES ('Villa Roulet');
INSERT INTO public.locations ( name) VALUES ('Santiago de Liniers');
INSERT INTO public.locations ( name) VALUES ('Eldorado');
INSERT INTO public.locations ( name) VALUES ('Comandante Andresito');
INSERT INTO public.locations ( name) VALUES ('Caburei');
INSERT INTO public.locations ( name) VALUES ('Dos Hermanas');
INSERT INTO public.locations ( name) VALUES ('Integración');
INSERT INTO public.locations ( name) VALUES ('Puerto Andresito');
INSERT INTO public.locations ( name) VALUES ('Puerto Deseado');
INSERT INTO public.locations ( name) VALUES ('San Antonio');
INSERT INTO public.locations ( name) VALUES ('Piñalito Norte');
INSERT INTO public.locations ( name) VALUES ('Bernardo de Irigoyen');
INSERT INTO public.locations ( name) VALUES ('El Soberbio');
INSERT INTO public.locations ( name) VALUES ('Fracrán');
INSERT INTO public.locations ( name) VALUES ('San Vicente');
INSERT INTO public.locations ( name) VALUES ('Puerto Libertad');
INSERT INTO public.locations ( name) VALUES ('Puerto Iguazú');
INSERT INTO public.locations ( name) VALUES ('Villa Cooperativa');
INSERT INTO public.locations ( name) VALUES ('Puerto Esperanza');
INSERT INTO public.locations ( name) VALUES ('Colonia Wanda');
INSERT INTO public.locations ( name) VALUES ('Almafuerte');
INSERT INTO public.locations ( name) VALUES ('Caá - Yarí');
INSERT INTO public.locations ( name) VALUES ('Cerro Azul');
INSERT INTO public.locations ( name) VALUES ('Dos Arroyos');
INSERT INTO public.locations ( name) VALUES ('Gobernador López');
INSERT INTO public.locations ( name) VALUES ('Leandro N. Alem');
INSERT INTO public.locations ( name) VALUES ('Olegario V. Andrade');
INSERT INTO public.locations ( name) VALUES ('Villa Libertad');
INSERT INTO public.locations ( name) VALUES ('Arroyo del Medio');
INSERT INTO public.locations ( name) VALUES ('Capioví');
INSERT INTO public.locations ( name) VALUES ('El Alcázar');
INSERT INTO public.locations ( name) VALUES ('Garuhapé');
INSERT INTO public.locations ( name) VALUES ('Mbopicuá');
INSERT INTO public.locations ( name) VALUES ('Puerto Rico');
INSERT INTO public.locations ( name) VALUES ('Ruiz de Montoya');
INSERT INTO public.locations ( name) VALUES ('San Alberto');
INSERT INTO public.locations ( name) VALUES ('San Miguel');
INSERT INTO public.locations ( name) VALUES ('Villa Akerman');
INSERT INTO public.locations ( name) VALUES ('Villa Urrutia');
INSERT INTO public.locations ( name) VALUES ('Puerto Leoni');
INSERT INTO public.locations ( name) VALUES ('San Gotardo');
INSERT INTO public.locations ( name) VALUES ('Capioviciño');
INSERT INTO public.locations ( name) VALUES ('Barrio Cuatro Bocas');
INSERT INTO public.locations ( name) VALUES ('Barrio Guatambu');
INSERT INTO public.locations ( name) VALUES ('Bario Ita');
INSERT INTO public.locations ( name) VALUES ('Laharrague');
INSERT INTO public.locations ( name) VALUES ('Montecarlo');
INSERT INTO public.locations ( name) VALUES ('Piray Kilómetro 18');
INSERT INTO public.locations ( name) VALUES ('Tarumá');
INSERT INTO public.locations ( name) VALUES ('Villa Parodi');
INSERT INTO public.locations ( name) VALUES ('Puerto Piray');
INSERT INTO public.locations ( name) VALUES ('Caraguatay');
INSERT INTO public.locations ( name) VALUES ('Colonia Alberdi');
INSERT INTO public.locations ( name) VALUES ('Barrio Escuela 633');
INSERT INTO public.locations ( name) VALUES ('Campo Ramón');
INSERT INTO public.locations ( name) VALUES ('Campo Viera');
INSERT INTO public.locations ( name) VALUES ('General Alvear');
INSERT INTO public.locations ( name) VALUES ('Guaraní');
INSERT INTO public.locations ( name) VALUES ('Los Helechos');
INSERT INTO public.locations ( name) VALUES ('Oberá');
INSERT INTO public.locations ( name) VALUES ('Panambí');
INSERT INTO public.locations ( name) VALUES ('Panambí Kilómetro 8');
INSERT INTO public.locations ( name) VALUES ('Panambi Kilómetro 15');
INSERT INTO public.locations ( name) VALUES ('Villa Bonita');
INSERT INTO public.locations ( name) VALUES ('San Martín');
INSERT INTO public.locations ( name) VALUES ('Barrio Escuela 461');
INSERT INTO public.locations ( name) VALUES ('El Salto');
INSERT INTO public.locations ( name) VALUES ('Colonia Polana');
INSERT INTO public.locations ( name) VALUES ('Corpus');
INSERT INTO public.locations ( name) VALUES ('Domingo Savio');
INSERT INTO public.locations ( name) VALUES ('General Urquiza');
INSERT INTO public.locations ( name) VALUES ('Gobernador Roca');
INSERT INTO public.locations ( name) VALUES ('Helvecia');
INSERT INTO public.locations ( name) VALUES ('Hipólito Yrigoyen');
INSERT INTO public.locations ( name) VALUES ('Oasis');
INSERT INTO public.locations ( name) VALUES ('Roca Chica');
INSERT INTO public.locations ( name) VALUES ('San Ignacio');
INSERT INTO public.locations ( name) VALUES ('Jardín América');
INSERT INTO public.locations ( name) VALUES ('Santo Pipó');
INSERT INTO public.locations ( name) VALUES ('Barrio Tungoil');
INSERT INTO public.locations ( name) VALUES ('Florentino Ameghino');
INSERT INTO public.locations ( name) VALUES ('Itacaruaré');
INSERT INTO public.locations ( name) VALUES ('Mojón Grande');
INSERT INTO public.locations ( name) VALUES ('San Javier');
INSERT INTO public.locations ( name) VALUES ('Paraíso');
INSERT INTO public.locations ( name) VALUES ('Piñalito Sur');
INSERT INTO public.locations ( name) VALUES ('San Pedro');
INSERT INTO public.locations ( name) VALUES ('Tobuna');
INSERT INTO public.locations ( name) VALUES ('Cruce Caballero');
INSERT INTO public.locations ( name) VALUES ('Alba Posse');
INSERT INTO public.locations ( name) VALUES ('Alicia Baja');
INSERT INTO public.locations ( name) VALUES ('Colonia Aurora');
INSERT INTO public.locations ( name) VALUES ('San Francisco de Asís');
INSERT INTO public.locations ( name) VALUES ('Santa Rita');
INSERT INTO public.locations ( name) VALUES ('25 de mayo');
INSERT INTO public.locations ( name) VALUES ('Alicia Alta');

INSERT INTO public.type_services ( description, isactive, name) VALUES ('Uso de dron para realizar la aplicación de un producto determinado, según area y tipo de plantación', true, 'Aplicación de Productos');
INSERT INTO public.type_services ( description, isactive, name) VALUES ('Servicio de control de estado de plantación por imágenes', true, 'Imagenes');

INSERT INTO public.types_plantations (active, description, name) VALUES (true, 'Son cultivos pertenecientes a la familia Poaceae o Gramíneas que normalmente se explotan en grandes extensiones y cuyos granos se caracterizan por su alto contenido en carbohidratos. Generalmente ese tipo de cultivo tiene un uso agroindustrial.', 'Cereales');
INSERT INTO public.types_plantations (active, description, name) VALUES (true, 'Pertenecen a la familia Fabaceae o Leguminosae que normalmente se explotan en grandes extensiones y cuyos granos se caracterizan por su alto contenido en proteínas. Generalmente se usan para consumo directo (no sufren un procesamiento agroindustrial). Ejemplos: caraota, frijol, quinchoncho.', 'Leguminosas');


INSERT INTO public.addresses (  location_id) VALUES ( 1);
INSERT INTO public.addresses (  location_id) VALUES ( 2);
INSERT INTO public.addresses (  location_id) VALUES ( 3);
INSERT INTO public.addresses (address, location_id) VALUES (NULL, NULL);
INSERT INTO public.addresses (address, location_id) VALUES ('Chacra 107', 2);


INSERT INTO public.contacts ( telephone) VALUES ( '3764373992');
INSERT INTO public.contacts (  telephone) VALUES ( '3764222222');
INSERT INTO public.contacts (  telephone) VALUES ( '3764333333');
INSERT INTO public.contacts (telephone) VALUES (NULL);
INSERT INTO public.contacts (telephone) VALUES (NULL);

INSERT INTO public.people (id, descriptions, dni, lastname, name, address_id, contact_id) VALUES (1, NULL, '32035722', 'Orozco', 'Cristian', 1, 1);
INSERT INTO public.people (id, descriptions, dni, lastname, name, address_id, contact_id) VALUES (2, NULL, '2222222', 'user02', 'user02', 2, 2);
INSERT INTO public.people (id, descriptions, dni, lastname, name, address_id, contact_id) VALUES (3, NULL, '3333333', 'user03', 'user03', 3, 3);
INSERT INTO public.people (id, descriptions, dni, lastname, name, address_id, contact_id) VALUES (4, NULL, NULL, NULL, NULL, 4, 4);

INSERT INTO public.users ( accountnonlocked, account_active, failedattempts,  password,  username) VALUES ( true, true, 0,  '$2a$10$I4enFYIa6YogBXLkYo9f4Oey6lC4GfuVdpV4tEjI2vDxdYYoiWH.q',  'orozcocristian860@gmail.com');
INSERT INTO public.users ( accountnonlocked, account_active, failedattempts,  password,  username) VALUES ( true, true, 0,  '$2a$10$I4enFYIa6YogBXLkYo9f4Oey6lC4GfuVdpV4tEjI2vDxdYYoiWH.q',  'user01@gmail.com');
INSERT INTO public.users ( accountnonlocked, account_active, failedattempts,  password,  username) VALUES ( true, true, 0,  '$2a$10$I4enFYIa6YogBXLkYo9f4Oey6lC4GfuVdpV4tEjI2vDxdYYoiWH.q',  'user02@gmail.com');
INSERT INTO public.users ( accountnonlocked, account_active, failedattempts,  password, username) VALUES (  true, true, 0,  '$2a$10$I4enFYIa6YogBXLkYo9f4Oey6lC4GfuVdpV4tEjI2vDxdYYoiWH.q', 'cristianwolf86@gmail.com');

INSERT INTO public.users_roles (user_id, role_id) VALUES (1, 1);
INSERT INTO public.users_roles (user_id, role_id) VALUES (1, 3);
INSERT INTO public.users_roles (user_id, role_id) VALUES (1, 2);
INSERT INTO public.users_roles (user_id, role_id) VALUES (2, 1);
INSERT INTO public.users_roles (user_id, role_id) VALUES (3, 3);
INSERT INTO public.users_roles (user_id, role_id) VALUES (4, 1);


INSERT INTO public.fields (active, dimensions, geolocation, name, observation, address_id, contact_id, person_id) VALUES (true, 1000, '10°38''26'''' - 10°38''26''''', 'Campito 1 Cristianwolf86', '', 5, 5, 4);


INSERT INTO public.plots (active, descriptions, dimensions, name, field_id, type_plantation_id) VALUES (true,'',540.43,'Lote Donna',1,2);
INSERT INTO public.plots (active, descriptions, dimensions, name, field_id, type_plantation_id) VALUES (true,'',600, 'Lote Kilian',1,1);
INSERT INTO public.plots (active, descriptions, dimensions, name, field_id, type_plantation_id) VALUES (true,'',600, 'Lote Silvana',1,2);
INSERT INTO public.plots (active, descriptions, dimensions, name, field_id, type_plantation_id) VALUES (false,'',680.8,'Lote La Gorda',1,1);